### ISSUE TITLE
 请问里面的bcc校验对吗？

### ISSUE THREAD

**Issue by 780662833** [soyoo/gocheck#1]
默认byte是10进制的 任何转化成16进制的byte

**Comment by soyoo** [comment]
> 默认byte是10进制的 任何转化成16进制的byte
应该是十六进制数

**Comment by 780662833** [comment]
byte是uint8的别名 10进制啊

**Comment by soyoo** [comment]
> byte是uint8的别名 10进制啊
bcc 计算的是十六进制数，为了表示十六进制数组，用了 []byte

**Comment by 780662833** [comment]
你好，我的理解 是golang的byte是10进制所以上面计算出来的结果也是10进制的bcc结果，然后把10进制转为16进制就是16进制的结果。非常感谢我已经得到了我想要的结果了
